name: CI & CD

on:
  push:
    branches-ignore:
      - master
    tags:
      - v*

jobs:
  Build-and-Release:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: Install Dependencies
        run: pnpm i --frozen-lockfile

      - name: Build Production
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: pnpm make

      - name: Release Production
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish
